apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bullmq-dashboard.fullname" . }}
  labels:
    app: {{ include "bullmq-dashboard.name" . }}
    version: {{ .Values.image.tag | quote }}
    {{- with .Values.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 2 }}
  progressDeadlineSeconds: {{ .Values.progressDeadlineSeconds | default 300 }}
  minReadySeconds: {{ .Values.minReadySeconds | default 0 }}
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable | default 0 }}
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge | default 1 }}
  selector:
    matchLabels:
      app: {{ include "bullmq-dashboard.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "bullmq-dashboard.name" . }}
        version: {{ .Values.image.tag | quote }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/chart: {{ print (toYaml .Values) (.Files.Glob "**" | toString) | sha256sum | quote }}
        sidecar.istio.io/inject: "{{ .Values.istio.injection }}"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
